#
# You can add custom slot machines by adding in slot_machines section:
#  
# name_of_your_slot_machine:
#   icons:
#     icon_name: image_path
#     # image_path requests for image in /assets/icons/
#   reels:
#     # List of reels
#     1:
#       # List of images on the reel
#       1: icon_name
#       2: icon_name
#     2: 
#       1: icon_name
#       2: icon_name
#
# If you don't specify any slot machines
# the default slot machine will be loaded.
#
slot_machines:
  default:
    icons:
      bulb: bulb.png
      exclamation: exclamation.png
      gamepad: gamepad.png
      gear: gear.png
      gnome: gnome.png
      ipod: ipod.png
      money: money.png
      ok: ok.png
      readonly: readonly.png
      science: science.png
      ubuntu: ubuntu.png
      web: web.png
      wrench: wrench.png
    lines_quantity: 3
    reels:
      1:
        1: bulb
        2: exclamation
        3: gamepad
        4: gear
        5: gnome
        6: ipod
        7: money
        8: ok
        9: readonly
        10: science
        11: ubuntu
        12: web
        13: wrench
      2:
        1: bulb
        2: gnome
        3: exclamation
        4: gear
        5: ipod
        6: money
        7: gamepad
        8: ok
        9: science
        10: readonly
        11: web
        12: wrench
        13: ubuntu
      3:
        1: web
        2: exclamation
        3: gnome
        4: ipod
        5: gear
        6: ok
        7: bulb
        8: readonly
        9: money
        10: gamepad
        11: science
        12: ubuntu
        13: wrench
      4:
        1: ubuntu
        2: web       
        3: gnome
        4: exclamation
        5: ipod
        6: ok
        7: bulb
        8: readonly
        9: wrench
        10: gamepad
        11: money
        12: science
        13: gear
      5:
        1: bulb
        2: exclamation
        3: gamepad
        4: gear
        5: gnome
        6: ipod
        7: money
        8: ok
        9: readonly
        10: science
        11: ubuntu
        12: web
        13: wrench
    combinations:
      # There are some default combinations such as full line of the same icons implemented in the model.
      # If you don't want to use them set enabled: false
      default:
        full_line: 
          sum: 100
          enabled: true
        in_line_4:
          sum: 70
          enabled: true
        in_line_3:
          sum: 50
          enabled: true
      # You can add your own combinations using syntax described below.
      custom:
        its_ok:
          sum: 200
          line:
            1: ok
            2: ok
            3: ok
            4: ok
            5: ok
  simple:
    icons:
      ubuntu: ubuntu.png
      bulb: bulb.png
      wrench: wrench.png
      gear: gear.png
      ipod: ipod.png
    lines_quantity: 1      
    reels:
      1:
        1: ipod
        2: bulb
        3: gear
        4: ubuntu
        5: wrench
      2:
        1: bulb
        2: gear
        3: ipod
        4: ubuntu
        5: wrench
      3:
        1: bulb
        2: ipod
        3: gear
        4: ubuntu
        5: wrench
    combinations:
      default:
        full_line: 
          sum: 100
          enabled: true
        in_line_4:
          sum: 70
          enabled: false
        in_line_3:
          sum: 50
          enabled: false